from googletrans import *


ui_key_tamil = ['பாரம்பரிய மருத்துவ பரிந்துரை முறை', 'எனக்கு நோய் பெயர் தெரியாது, அறிகுறிகளில் உள்ளிட விரும்புகிறேன்',
                 'எனக்கு நோய் பெயர் தெரியும்', 'நோய் நோயறிதல் தாவல்', 'அறிகுறிகளைத் தேர்ந்தெடுக்கவும்', 'சேர்', 'அகற்று',
                 'நோயறிதல்', 'நோய் நுழைவு தாவல்', 'நோய் பெயர்:', 'உறுதிப்படுத்தவும்', 'மருந்து பரிந்துரை பகுதி',
                 'நோய் பெயர்:', 'மருந்து வகை:', 'மருத்துவத்தை உறுதிப்படுத்தவும் பெறவும்',
                 'பரிந்துரைக்கப்பட்ட மருத்துவத்தின் பட்டியல் :', '(குறிப்பு: தயவுசெய்து சரியான நோயை உள்ளிடவும். '
                                                                 '"உறுதிப்படுத்த" பொத்தானை அழுத்துவதற்கு முன் நோய் '
                                                                 'பெயர் எழுத்துப்பிழை சரிபார்க்கவும்)', 'மொழி']
ui_key_english = ["Traditional medicine recommendation system",
                  "I don't know the disease name, I want to enter the symptoms", "I know the disease name",
                  "Disease Diagnosis Tab", "Select the symptoms", "Add", "Remove", "Diagnosis", "Disease Entry Tab",
                  "Disease Name : ", "Confirm", "Medicine Recommendation Area", "Disease name : ", "Medicine Type : ",
                  "Confirm and Fetch Medicine", "List of Medicine suggested : ",
                  "(Note: Please enter a valid disease. Before pressing \"Confirm\" button please verify disease name "
                  "spelling)", 'Lang']
ui_size_english = []
med_type_in_tamil = ['ஆயுர்வேதம்', 'சித்தா', 'யுனானி']
med_type_in_english = ['Ayurveda', 'Siddha', 'Unani']
ui_size_tamil = []
english_font = []
tamil_font = []
lang_ = ["English", "தமிழ்"]

symptoms_english = ['increased appetite', 'bladder discomfort', 'pain behind the eyes', 'weakness of one body side', 'enlarged thyroid', 'patches in throat', 'muscle wasting', 'blood in sputum', 'itching', 'indigestion', 'restlessness', 'yellowish skin', 'abnormal menstruation', 'stomach bleeding', 'irritability', 'yellow crust ooze', 'blackheads', 'fluid overload.1', 'acute liver failure', 'headache', 'chest pain', 'ulcers on tongue', 'prognosis', 'bruising', 'puffy face and eyes', 'nausea', 'coma', 'hip joint pain', 'painful walking', 'history of alcohol consumption', 'excessive hunger', 'swelling of stomach', 'swollen blood vessels', 'depression', 'high fever', 'back pain', 'unsteadiness', 'movement stiffness', 'foul smell of urine', 'palpitations', 'loss of appetite', 'stomach pain', 'pus filled pimples', 'visual disturbances', 'muscle pain', 'mucoid sputum', 'continuous sneezing', 'belly pain', 'receiving unsterile injections', 'acidity', 'watering from eyes', 'phlegm', 'slurred speech', 'brittle nails', 'lack of concentration', 'weight loss', 'inflammatory nails', 'vomiting', 'lethargy', 'passage of gases', 'diarrhoea', 'red spots over body', 'prominent veins on calf', 'weight gain', 'mood swings', 'loss of smell', 'weakness in limbs', 'joint pain', 'yellowing of eyes', 'irritation in anus', 'cramps', 'drying and tingling lips', 'blurred and distorted vision', 'toxic look typhos', 'red sore around nose', 'knee pain', 'sinus pressure', 'anxiety', 'obesity', 'throat irritation', 'scurring', 'neck pain', 'loss of balance', 'dark urine', 'extra marital contacts', 'irregular sugar level', 'polyuria', 'yellow urine', 'blister', 'nodal skin eruptions', 'pain during bowel movements', 'swelling joints', 'runny nose', 'fast heart rate', 'swollen extremeties', 'rusty sputum', 'skin peeling', 'bloody stool', 'dehydration', 'sweating', 'dischromic patches', 'burning micturition', 'swelled lymph nodes', 'mild fever', 'muscle weakness', 'small dents in nails', 'family history', 'fluid overload', 'receiving blood transfusion', 'continuous feel of urine', 'dizziness', 'fatigue', 'cough', 'altered sensorium', 'skin rash', 'swollen legs', 'malaise', 'abdominal pain', 'constipation', 'silver like dusting', 'breathlessness', 'pain in anal region', 'spotting urination', 'cold hands and feets', 'internal itching', 'spinning movements', 'chills', 'distention of abdomen', 'redness of eyes', 'stiff neck', 'shivering', 'sunken eyes', 'congestion']
symptoms_tamil = ['அதிகரித்த பசி', 'சிறுநீர்ப்பை அச om கரியம்', 'கண்களுக்கு பின்னால் வலி', 'ஒரு உடல் பக்கத்தின் பலவீனம்', 'விரிவாக்கப்பட்ட தைராய்டு', 'தொண்டையில் திட்டுகள்', 'தசை சுருக்கம்', 'ஸ்பூட்டத்தில் இரத்தம்', 'அரிப்பு', 'அஜீரணம்', 'ஓய்வின்மை', 'மஞ்சள் நிற தோல்', 'அசாதாரண மாதவிடாய்', 'வயிற்று இரத்தப்போக்கு', 'எரிச்சல்', 'மஞ்சள் மேலோடு ஓஸ்', 'பிளாக்ஹெட்ஸ்', 'திரவ ஓவர்லோட் 1', 'கடுமையான கல்லீரல் செயலிழப்பு', 'தலைவலி', 'நெஞ்சு வலி', 'நாக்கில் புண்கள்', 'முன்கணிப்பு', 'சிராய்ப்பு', 'பஃபி முகம் மற்றும் கண்கள்', 'குமட்டல்', 'கோமா', 'இடுப்பு மூட்டு வலி', 'வலி நடைபயிற்சி', 'மது அருந்தும் வரலாறு', 'அதிகப்படியான பசி', 'வயிற்றின் வீக்கம்', 'வீங்கிய இரத்த நாளங்கள்', 'மனச்சோர்வு', 'அதிக காய்ச்சல்', 'முதுகு வலி', 'நிலையற்ற தன்மை', 'இயக்கம் விறைப்பு', 'சிறுநீரின் தவறான வாசனை', 'படபடப்பு', 'பசியிழப்பு', 'வயிற்று வலி', 'சீழ் நிரப்பப்பட்ட பருக்கள்', 'காட்சி இடையூறுகள்', 'தசை வலி', 'மியூகோயிட் ஸ்பூட்டம்', 'தொடர்ச்சியான தும்மல்', 'தொப்பை வலி', 'அன்ஸ்டெரெடில் ஊசி பெறுதல்', 'அமிலத்தன்மை', 'கண்களிலிருந்து நீர்ப்பாசனம்', 'கபம்', 'தெளிவற்ற பேச்சு', 'உடையக்கூடிய நகங்கள்', 'செறிவு இல்லாமை', 'எடை இழப்பு', 'அழற்சி நகங்கள்', 'வாந்தி', 'சோம்பல்', 'வாயுக்களின் பாதை', 'வயிற்றுப்போக்கு', 'உடலுக்கு மேல் சிவப்பு புள்ளிகள்', 'கன்று மீது முக்கிய நரம்புகள்', 'எடை அதிகரிப்பு', 'மனம் அலைபாயிகிறது', 'வாசனை இழப்பு', 'கைகால்களில் பலவீனம்', 'மூட்டு வலி', 'கண்களின் மஞ்சள்', 'ஆசனவாய் எரிச்சல்', 'பிடிப்புகள்', 'உலர்த்துதல் மற்றும் கூச்ச உதடுகள்', 'மங்கலான மற்றும் சிதைந்த பார்வை', 'நச்சு தோற்றம் டைபோஸ்', 'மூக்கைச் சுற்றி சிவப்பு புண்', 'மூட்டு வலி', 'சைனஸ் அழுத்தம்', 'கவலை', 'உடல் பருமன்', 'தொண்டை எரிச்சல்', 'திணறல்', 'கழுத்து வலி', 'சமநிலை இழப்பு', 'இருண்ட சிறுநீர்', 'கூடுதல் திருமண தொடர்புகள்', 'ஒழுங்கற்ற சர்க்கரை நிலை', 'பாலியூரியா', 'மஞ்சள் சிறுநீர்', 'கொப்புளம்', 'நோடல் தோல் வெடிப்புகள்', 'குடல் இயக்கங்களின் போது வலி', 'வீக்கம் மூட்டுகள்', 'மூக்கு ஒழுகுதல்', 'வேகமான இதய துடிப்பு', 'வீங்கிய முனைகள்', 'ரஸ்டி ஸ்பூட்டம்', 'தோல் உரித்தல்', 'இரத்தக்களரி மலம்', 'நீரிழப்பு', 'வியர்வை', 'அவதூறு திட்டுகள்', 'எரியும் மிக்டரிஷன்', 'வீங்கிய நிணநீர் கணுக்கள்', 'லேசான காய்ச்சல்', 'தசை பலவீனம்', 'நகங்களில் சிறிய பற்கள்', 'குடும்ப வரலாறு', 'திரவ ஓவர்லோட்', 'இரத்தமாற்றம் பெறுதல்', 'சிறுநீரின் தொடர்ச்சியான உணர்வு', 'தலைச்சுற்றல்', 'சோர்வு', 'இருமல்', 'மாற்றப்பட்ட சென்சோரியம்', 'தோல் வெடிப்பு', 'வீங்கிய கால்கள்', 'உடல்நலக்குறைவு', 'வயிற்று வலி', 'மலச்சிக்கல்', 'தூசி போன்ற வெள்ளி', 'மூச்சுத் திணறல்', 'குத பகுதியில் வலி', 'சிறுநீர் கழிப்பதைக் கண்டறிதல்', 'குளிர் கைகள் மற்றும் கால்கள்', 'உள் அரிப்பு', 'சுழல் இயக்கங்கள்', 'சளி', 'அடிவயிற்றின் விலகல்', 'கண்களின் சிவத்தல்', 'பிடிப்பான கழுத்து', 'நடுக்கம்', 'மூழ்கிய கண்கள்', 'நெரிசல்']

